### ISSUE TITLE
Use System.nanotime() instead System.currentTimeMillis()

### ISSUE THREAD

**Issue by czyrux** [NikitaKozlov/Pury#6]
In order to have more accurate measurement use System.nanoTime() instead System.currentTimeMillis() in [StopWatch](https://github.com/NikitaKozlov/Pury/blob/master/pury/src/main/java/com/nikitakozlov/pury/internal/profile/StopWatch.java#L17)

**Comment by hujiaweibujidao** [comment]
+1, agreed with @czyrux 

`System.nanoTime()` offers better precision and accuracy.

**Comment by NikitaKozlov** [comment]
Thanks for opening an issue.
Pury can't offer nano seconds precision, because Aspects run in a Thread where method is called, so in case of `@StopProfiling` it affects the measurement. Result processing is also not going into a separate Thread.
Nonetheless, I will definitely change `System.currentTimeMillis()` to something else. But because of a different issue. `System.currentTimeMillis()` returns a wall time, time that user can change. I didn't decided yet if I should go for a nanoTime or for elapsed time.

**Comment by NikitaKozlov** [comment]
Fixed. https://github.com/NikitaKozlov/Pury/pull/9
